import { describe, expect, it } from "vitest";

import fixture from "./fixtures/mock-ipc-contract-v1.json";
import * as contractModule from "./mockIpcContract";
import { createMockIpcReplay, validateMockIpcContractV1 } from "./mockIpcContract";

const cloneFixture = (): unknown => structuredClone(fixture);

describe("MockIpcContractV1", () => {
  it("validates the Rust-generated fixture and consumes exact exchanges", () => {
    const contract = validateMockIpcContractV1(fixture);
    const replay = createMockIpcReplay(contract, "fixture-validation");

    expect(replay.invoke("search_vault", { query: "neural" })).toEqual({
      hits: [],
      truncated: false,
      skippedFiles: 0,
    });
    expect(replay.remaining()).toBe(0);
  });

  it("fails loudly when a command argument drifts", () => {
    const contract = validateMockIpcContractV1(fixture);
    const replay = createMockIpcReplay(contract, "fixture-validation");

    expect(() => replay.invoke("search_vault", { query: "changed" })).toThrow(
      /argument drift.*search_vault/u,
    );
  });

  it("retains the scenario's complete owned command set after exchanges are consumed", () => {
    const contract = validateMockIpcContractV1(fixture);
    const replay = createMockIpcReplay(contract, "templates-feature");
    const ownsCommand = (
      replay as typeof replay & { ownsCommand?: (command: string) => boolean }
    ).ownsCommand;

    expect(ownsCommand).toBeTypeOf("function");
    expect(ownsCommand?.("list_templates")).toBe(true);
    expect(ownsCommand?.("create_note_from_template")).toBe(true);
    expect(ownsCommand?.("read_note")).toBe(false);

    replay.invoke("list_templates", {});
    expect(ownsCommand?.("list_templates")).toBe(true);
  });

  it("exposes the one validated Rust-generated contract consumed by mock constants", () => {
    expect(contractModule).toHaveProperty("MOCK_IPC_CONTRACT_V1");
    expect(
      (contractModule as { MOCK_IPC_CONTRACT_V1?: unknown }).MOCK_IPC_CONTRACT_V1,
    ).toEqual(validateMockIpcContractV1(fixture));
  });

  it("rejects missing or additional V1 constant fields", () => {
    const missing = cloneFixture() as {
      constants: Record<string, unknown>;
    };
    delete missing.constants.maxEditableNoteBytes;
    expect(() => validateMockIpcContractV1(missing)).toThrow(
      /constants.*maxEditableNoteBytes/u,
    );

    const additional = cloneFixture() as {
      constants: Record<string, unknown>;
    };
    additional.constants.unversionedLimit = 1;
    expect(() => validateMockIpcContractV1(additional)).toThrow(
      /constants.*unversionedLimit/u,
    );
  });

  it("rejects missing, mismatched, or unknown V1 typed-error fields", () => {
    const missing = cloneFixture() as {
      errors: Record<string, unknown>;
    };
    delete missing.errors.notFound;
    expect(() => validateMockIpcContractV1(missing)).toThrow(/errors.*notFound/u);

    const mismatched = cloneFixture() as {
      errors: Record<string, { kind: string; message: string }>;
    };
    mismatched.errors.notFound.kind = "io";
    expect(() => validateMockIpcContractV1(mismatched)).toThrow(
      /errors\.notFound.*notFound/u,
    );

    const unknown = cloneFixture() as {
      errors: Record<string, unknown>;
    };
    unknown.errors.futureError = { kind: "futureError", message: "fixture" };
    expect(() => validateMockIpcContractV1(unknown)).toThrow(/errors.*futureError/u);
  });

  it("replays the exact typed error produced by the real Rust core", () => {
    const contract = validateMockIpcContractV1(fixture);
    const replay = createMockIpcReplay(contract, "backlinks-missing-target");

    let rejection: unknown;
    try {
      replay.invoke("read_backlinks", { path: "/vault/Missing.md" });
    } catch (error) {
      rejection = error;
    }

    expect(rejection).toEqual({ kind: "notFound", message: "Missing.md" });
    expect(replay.remaining()).toBe(0);
  });

  it("rejects an exchange error kind outside the generated Rust catalog", () => {
    const drifted = cloneFixture() as {
      scenarios: Record<string, unknown>;
    };
    drifted.scenarios["drifted-error"] = [
      {
        command: "read_note",
        arguments: { path: "/vault/Note.md" },
        error: { kind: "futureError", message: "not generated by Rust" },
      },
    ];

    expect(() => validateMockIpcContractV1(drifted)).toThrow(
      /drifted-error.*futureError/u,
    );
  });
});
