// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a live activity had to be closed by terminal run bookkeeping.
 */
export type ActivityAbandonReason = "runCompleted" | "runFailed";
