// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentActivityPayload } from "./AgentActivityPayload";

/**
 * One causally ordered item in an agentic turn's activity journal.
 */
export type AgentActivityEnvelope = { schemaVersion: number, turnId: string, sequence: number, cycleId: string | null, activityId: string | null, payload: AgentActivityPayload, };
