// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalStatus } from "./LocalStatus";
import type { OpenRouterStatus } from "./OpenRouterStatus";
import type { ProviderKind } from "./ProviderKind";
import type { ReasoningSupport } from "./ReasoningSupport";

/**
 * Provider-aware AI status for the settings UI and the chat pane's first-run
 * decision. `active_provider` is the *effective* provider (an existing key user
 * with no explicit choice reads as OpenRouter), or `null` when nothing is set up
 * yet. This is a pure config read — it never starts the sidecar or touches the
 * keychain, so the UI can poll it cheaply.
 */
export type AiStatus = { activeProvider: ProviderKind | null, reasoningSupported: ReasoningSupport, openrouter: OpenRouterStatus, local: LocalStatus, };
