// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppPreferences } from "./AppPreferences";

/**
 * Load outcome kept distinct from I/O failure: corrupt JSON has a safe launch
 * fallback, but the host must surface `recovery_message` persistently and use
 * `recovered_from_corrupt` to suppress background update checks for this launch.
 */
export type AppPreferencesLoad = { preferences: AppPreferences, recoveredFromCorrupt: boolean, recoveryMessage: string | null, };
