// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontFamily } from "./FontFamily";
import type { FontScale } from "./FontScale";
import type { ThemeId } from "./ThemeId";

export type AppPreferences = { automaticUpdateChecks: boolean, theme: ThemeId, fontScale: FontScale, fontFamily: FontFamily, lastSeenWhatsNewVersion: string | null, };
