// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A compiled-in rule id. The judge may only *name* a rule from this closed set,
 * so a model cannot smuggle text back through the `rule` field.
 */
export type ApprovalRule = "yolo" | "newNoteInVault" | "cachedAllow";
