// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much the agent may do without asking.
 *
 * Variant ORDER IS LOAD-BEARING TWICE: `Default` takes the first variant (the
 * safe one), and the derived `Ord` makes `min(a, b)` mean "the more restrictive
 * of the two", which is how a per-tool override clamps the global mode
 * (§9.6.4). Reordering these silently makes YOLO the default AND inverts the
 * clamp — hence [`the_order_is_most_restrictive_first`](self#tests), which fails
 * loudly if anyone does.
 */
export type ApprovalMode = "alwaysAsk" | "approveForMe" | "yolo";
