// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why automatic checking stopped for the rest of a run.
 */
export type ApprovalDegradedReason = "providerUnsupported" | "judgeUnreliable";
