// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalMode } from "./ApprovalMode";

/**
 * Everything the Settings page needs to render the approval controls, computed
 * in Rust so the UI never derives a security value for itself.
 */
export type ApprovalStatus = { 
/**
 * The stored global default.
 */
mode: ApprovalMode, 
/**
 * The stored per-tool exceptions, exactly as persisted.
 */
toolOverrides: { [key in string]: ApprovalMode }, 
/**
 * What each gated tool ACTUALLY resolves to once the global ceiling and the
 * compiled-in defaults are applied. A stored override that is less
 * restrictive than the global is inert, and the UI has to be able to show it
 * as inactive — an override that silently does nothing is its own small lie.
 */
effectiveModes: { [key in string]: ApprovalMode }, 
/**
 * Whether the active provider can run the judge. `false` on the local lane,
 * where "Approve for me" renders disabled with its reason inline and the
 * user's stored preference is left untouched.
 */
classifierAvailable: boolean, 
/**
 * The plain-language consequences of every irreversible tool, in order,
 * generated from the reversibility classification. The UI composes the
 * sentence around this list; it must never hand-write one, or the warning can
 * rot into a stale list and silently omit a newly-added destructive tool.
 */
irreversibleActions: Array<string>, };
