// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an approval settled.
 *
 * A deliberate departure from `Elicit`, which emits no follow-up because
 * presentation state is client-side. For a security prompt that is wrong: a
 * timeout or a window close must be visible, or the UI leaves a security sheet
 * on screen that silently no-ops.
 */
export type ApprovalResolution = "approved" | "denied" | "timedOut" | "cancelled" | "unavailable";
