// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the user is being asked. A closed enum, never free text: the prompt's copy
 * is compiled in on both sides, so a security question's wording can never be
 * model-authored (`ask_user` lets the model write its own question text, which
 * is exactly why approvals do not reuse it).
 */
export type ApprovalReason = "modeAlwaysAsk" | "irreversible" | "notEligible" | "judgeAsked" | "judgeUnavailable" | "providerUnsupported" | "previouslyDenied";
