// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One resolved occurrence of a link pointing at the current note.
 */
export type Backlink = { sourceRel: string, sourceTitle: string, snippet: string, 
/**
 * 1-based line number in the source note body.
 */
line: number, };
