// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backlink } from "./Backlink";
import type { UnlinkedMention } from "./UnlinkedMention";

/**
 * The Obsidian-style backlinks panel payload.
 */
export type Backlinks = { linked: Array<Backlink>, unlinked: Array<UnlinkedMention>, 
/**
 * Markdown files that could not be read and were skipped (each is also
 * logged). Lets the UI distinguish "no mentions" from "couldn't look".
 */
skippedFiles: number, };
