// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CancelChatRunStatus } from "./CancelChatRunStatus";

export type CancelChatRunOutcome = { turnId: string, status: CancelChatRunStatus, };
