// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CandidateModel = { tag: string, params: string, downloadBytes: number, minRamBytes: number, license: string, hfRepo: string, };
