// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElicitOption } from "./ElicitOption";
import type { NoteKind } from "./NoteKind";

/**
 * One event in a chat run's stream. Emitted in causal order; a run ends with
 * either [`ChatEvent::Done`] (success) or [`ChatEvent::Error`] (surfaced failure)
 * — never silently.
 */
export type ChatEvent = { "type": "processing" } | { "type": "skillActivated", id: string, name: string, } | { "type": "skillStep", message: string, } | { "type": "elicit", id: string, question: string, options: Array<ElicitOption>, multiSelect: boolean, } | { "type": "noteWritten", relPath: string, kind: NoteKind, } | { "type": "searching", query: string, } | { "type": "retrieved", query: string, hitCount: number, } | { "type": "reading", relPath: string, startLine: number, endLine: number, } | { "type": "thinking", delta: string, } | { "type": "verifying" } | { "type": "citationDropped", reason: string, } | { "type": "answer", delta: string, } | { "type": "answerTruncated" } | { "type": "citation", id: string, relPath: string, startLine: number, endLine: number, text: string, } | { "type": "coverage", searchedTerms: Array<string>, notesRead: Array<string>, truncated: boolean, skippedFiles: number, } | { "type": "error", message: string, } | { "type": "done" };
