// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElicitOption } from "./ElicitOption";
import type { NoteKind } from "./NoteKind";
import type { ToolStatus } from "./ToolStatus";

/**
 * One event in a chat run's stream. Emitted in causal order; a run ends with
 * either [`ChatEvent::Done`] (success) or [`ChatEvent::Error`] (surfaced failure)
 * — never silently.
 */
export type ChatEvent = { "type": "processing" } | { "type": "skillActivated", id: string, name: string, } | { "type": "skillStep", message: string, } | { "type": "elicit", id: string, question: string, options: Array<ElicitOption>, multiSelect: boolean, } | { "type": "skillActivationFailed", id: string, name: string, 
/**
 * The human sentence, for display only — no longer load-bearing.
 */
message: string, missingBinary: string | null, } | { "type": "toolCall", 
/**
 * The provider's call id — the correlation key for every later event.
 */
id: string, 
/**
 * The registered tool name (one of the `TOOL_*` constants in `ai/tools.rs`).
 */
name: string, 
/**
 * A human label from the Rust-side table in [`crate::ai::tool_registry`].
 * NEVER model prose — that is the coupling this event exists to kill.
 */
title: string, 
/**
 * The raw arguments JSON exactly as the model emitted it. The UI parses it
 * defensively for the detail line; it is never trusted to be valid JSON.
 */
arguments: string, } | { "type": "toolResult", id: string, status: ToolStatus, 
/**
 * A Rust-composed one-liner ("12 spans"), never model prose.
 */
summary: string | null, 
/**
 * Bounded result or error text for the disclosure. Truncated Rust-side.
 */
detail: string | null, } | { "type": "transcriptSource", label: string, relPath: string | null, } | { "type": "partialRun", reason: string, } | { "type": "noteWritten", relPath: string, kind: NoteKind, } | { "type": "noteExists", relPath: string, kind: NoteKind, } | { "type": "searching", query: string, } | { "type": "retrieved", query: string, hitCount: number, } | { "type": "reading", relPath: string, startLine: number, endLine: number, } | { "type": "thinking", delta: string, } | { "type": "verifying" } | { "type": "citationDropped", reason: string, } | { "type": "answer", delta: string, } | { "type": "answerTruncated" } | { "type": "citation", id: string, relPath: string, startLine: number, endLine: number, text: string, } | { "type": "coverage", searchedTerms: Array<string>, notesRead: Array<string>, truncated: boolean, skippedFiles: number, } | { "type": "error", message: string, } | { "type": "done" };
