// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDegradedReason } from "./ApprovalDegradedReason";
import type { ApprovalReason } from "./ApprovalReason";
import type { ApprovalResolution } from "./ApprovalResolution";
import type { ApprovalRule } from "./ApprovalRule";
import type { ElicitOption } from "./ElicitOption";
import type { GatedTool } from "./GatedTool";
import type { NoteKind } from "./NoteKind";
import type { PlanStep } from "./PlanStep";
import type { PlaylistPosition } from "./PlaylistPosition";
import type { StepStatus } from "./StepStatus";
import type { ToolStatus } from "./ToolStatus";

/**
 * One event in a chat run's stream. Emitted in causal order; a run ends with
 * either [`ChatEvent::Done`] (success) or [`ChatEvent::Error`] (surfaced failure)
 * — never silently.
 */
export type ChatEvent = { "type": "processing" } | { "type": "planningRound", 
/**
 * 1-based. The first tool-deciding turn is round 1.
 */
round: number, 
/**
 * Current ceiling; skill activation can raise it. Render the latest
 * value rather than caching the initial denominator.
 */
maxRounds: number, 
/**
 * Current playlist item, or `None` outside a playlist. Repeated each
 * round to clear stale progress. Playlist length is fixed; each item
 * has its own iteration allowance.
 */
playlist: PlaylistPosition | null, } | { "type": "keepalive" } | { "type": "toolProgress", 
/**
 * The [`ChatEvent::ToolCall`] id.
 */
id: string, message: string, } | { "type": "videoPreview", 
/**
 * The YouTube video id, so a card can be told apart from its successor
 * even when two videos share a title.
 */
videoId: string, title: string, 
/**
 * Absent when the extractor reported no duration — which it does — and
 * an absent duration must render as absent rather than as `0`.
 */
durationSecs: number | null, channel: string | null, 
/**
 * Host-validated, bounded data URI; no third-party webview allowlist.
 * Fetch failure, rejection, or timeout produces `None` without failing
 * the run. The card must remain useful without a thumbnail.
 */
thumbnailDataUri: string | null, } | { "type": "skillActivated", id: string, name: string, } | { "type": "skillStep", message: string, } | { "type": "elicit", id: string, question: string, options: Array<ElicitOption>, multiSelect: boolean, } | { "type": "skillActivationFailed", id: string, name: string, 
/**
 * The human sentence, for display only — no longer load-bearing.
 */
message: string, missingBinary: string | null, } | { "type": "toolCall", 
/**
 * The provider's call id — the correlation key for every later event.
 */
id: string, 
/**
 * The registered tool name (one of the `TOOL_*` constants in `ai/tools.rs`).
 */
name: string, 
/**
 * A human label from the Rust-side table in [`crate::ai::tool_registry`].
 * NEVER model prose — that is the coupling this event exists to kill.
 */
title: string, 
/**
 * The raw arguments JSON exactly as the model emitted it. The UI parses it
 * defensively for the detail line; it is never trusted to be valid JSON.
 */
arguments: string, 
/**
 * The step running at dispatch. Later plan changes must not re-parent
 * this call. `None` means no active step, including the call that creates
 * the plan. Settlement correlates on `id`, independently of this field.
 */
stepId: string | null, } | { "type": "toolResult", id: string, status: ToolStatus, 
/**
 * A Rust-composed one-liner ("12 spans"), never model prose.
 */
summary: string | null, 
/**
 * Bounded result or error text for the disclosure. Truncated Rust-side.
 */
detail: string | null, 
/**
 * Elapsed time measured with `Instant` from dispatch to settlement,
 * including any approval wait. This is not tool execution time.
 */
durationMs: number, } | { "type": "transcriptSource", label: string, relPath: string | null, } | { "type": "partialRun", reason: string, } | { "type": "noteWritten", relPath: string, kind: NoteKind, } | { "type": "noteExists", relPath: string, kind: NoteKind, } | { "type": "noteEditPreview", 
/**
 * The [`ChatEvent::ToolCall`] id, so the card upgrades in place into
 * [`ChatEvent::NoteWritten`] rather than becoming a second node.
 */
id: string, 
/**
 * Absent until the path member has finished arriving — half a path must
 * never be shown as if it were the whole path.
 */
relPath: string | null, kind: NoteKind | null, 
/**
 * The note body composed SO FAR, already un-escaped.
 */
body: string, 
/**
 * The arguments JSON has closed and parses. **The write has NOT happened
 * yet** — the tool still has to be dispatched, and can still be rejected.
 */
complete: boolean, } | { "type": "noteEditAbandoned", id: string, reason: string, } | { "type": "toolApprovalChecking", id: string, } | { "type": "toolApprovalRequested", 
/**
 * The [`ChatEvent::ToolCall`] id, so the sheet attaches to that node.
 */
id: string, tool: GatedTool, 
/**
 * The vault-relative path, **for the human**. Deliberately absent from
 * the judge's input: a person can read a deceptive filename and is the
 * right party to judge it; a classifier cannot.
 */
relPath: string | null, 
/**
 * A compiled-in reason, never free text and never model prose.
 */
reason: ApprovalReason, expiresInSecs: number, } | { "type": "toolAutoApproved", id: string, tool: GatedTool, rule: ApprovalRule, } | { "type": "toolApprovalResolved", id: string, decision: ApprovalResolution, } | { "type": "toolApprovalDegraded", reason: ApprovalDegradedReason, } | { "type": "searching", query: string, 
/**
 * The [`ChatEvent::ToolCall`] that ran it — see [`ChatEvent::Retrieved`].
 */
callId: string | null, } | { "type": "retrieved", query: string, hitCount: number, callId: string | null, } | { "type": "reading", relPath: string, startLine: number, endLine: number, 
/**
 * The [`ChatEvent::ToolCall`] that read it — see [`ChatEvent::Retrieved`].
 */
callId: string | null, } | { "type": "thinking", delta: string, } | { "type": "verifying" } | { "type": "citationDropped", reason: string, } | { "type": "answer", delta: string, } | { "type": "answerTruncated" } | { "type": "citation", id: string, relPath: string, startLine: number, endLine: number, text: string, } | { "type": "coverage", searchedTerms: Array<string>, notesRead: Array<string>, truncated: boolean, skippedFiles: number, } | { "type": "plan", steps: Array<PlanStep>, } | { "type": "planStepStatus", id: string, status: StepStatus, } | { "type": "usage", elapsedMs: number, tokensIn: number | null, tokensOut: number | null, model: string, } | { "type": "error", message: string, } | { "type": "done" };
