// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoreError = { "kind": "notFound", "message": string } | { "kind": "alreadyExists", "message": string } | { "kind": "outsideVault", "message": string } | { "kind": "invalidName", "message": string } | { "kind": "invalidContent", "message": string } | { "kind": "conflict", "message": string } | { "kind": "io", "message": string } | { "kind": "frontmatter", "message": string } | { "kind": "llm", "message": string } | { "kind": "localAi", "message": string };
