// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the visible cycle summary came from the model or a bounded host
 * fallback. Legacy [`ChatEvent::SkillStep`] messages never become this type.
 */
export type CycleSummarySource = "model" | "fallback";
