// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bounded, non-sensitive diagnostics for malformed administrative calls.
 *
 * These variants never contain raw arguments, parser errors, provider ids, or
 * model prose. An arbitrary batch can therefore create only a small fixed
 * payload and cannot smuggle vault content into a diagnostic surface.
 */
export type CycleSummaryProtocolIssue = { "kind": "malformedArguments" } | { "kind": "emptyMessage" } | { "kind": "multipleParagraphs" } | { "kind": "controlCharacter" } | { "kind": "tooLong" } | { "kind": "duplicate" } | { "kind": "late" } | { "kind": "missing" } | { "kind": "additional", count: number, };
