// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TreeNode } from "./TreeNode";

/**
 * One directory's immediate children, for the lazy file-tree DISPLAY path only.
 * Produced by [`crate::tree::list_dir`]; never consumed by search, the link
 * graph, backlinks, or AI retrieval — those keep scanning the whole vault.
 */
export type DirListing = { 
/**
 * One level of children, folders-first then files (case-insensitive by
 * name). Folder entries carry `children: None`, meaning "not loaded yet" —
 * distinct from a file's `None`, disambiguated by `kind`.
 */
entries: Array<TreeNode>, 
/**
 * `Some(n)` = n further entries in THIS directory were omitted by the
 * per-directory cap; `None` = complete listing. Drives an explicit
 * "N more…" row so truncation is never silent.
 */
truncated: number | null, };
