// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable answer shown by an [`Elicitation`]. Images stay data URIs so a
 * webview never needs a third-party network allowlist.
 */
export type ElicitOption = { id: string, label: string, description: string | null, imageDataUri: string | null, };
