// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElicitOption } from "./ElicitOption";

/**
 * A structured question the core asks through the host-provided prompt seam.
 */
export type Elicitation = { id: string, question: string, options: Array<ElicitOption>, multiSelect: boolean, };
