// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a tree node is a folder or a file.
 */
export type EntryKind = "folder" | "file";
