// This file was generated from the Rust event-name constants by `cargo test`
// (app/desktop/src-tauri/src/event_names.rs). Do not edit this file manually.

/** Emitted by the shell when the open vault changes on disk. */
export const TREE_CHANGED = "vault://tree-changed";
/** Emitted by the native menu for every custom action. */
export const MENU_ACTION = "menu://action";
