// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchMatch } from "./SearchMatch";

/**
 * One file's worth of search results.
 */
export type FileHit = { 
/**
 * Absolute path on disk.
 */
path: string, relPath: string, title: string, 
/**
 * True when the file stem or title matched the query (ranked first).
 */
nameMatch: boolean, 
/**
 * Content matches; empty for a name-only hit.
 */
matches: Array<SearchMatch>, };
