// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tool the approval gate covers.
 *
 * **Closed on purpose, and there is deliberately no `Other(String)` variant.**
 * A string variant would reopen the injection channel this whole design closes:
 * the classifier's input is a fixed set of app-computed scalars precisely so
 * that no field exists for an instruction to live in. One `String` is enough to
 * undo that, so the escape hatch is not offered.
 *
 * The wire name of each variant is a `TOOL_*` constant from
 * [`crate::ai::tool_registry`], and
 * [`every_gated_tool_name_is_a_registered_tool`](self#tests) keeps the two
 * tables tied together — a tool rename cannot silently un-gate a tool.
 */
export type GatedTool = "writeNote" | "useSkill" | "selectPlaylistVideos" | "resolveDistilRoute" | "fetchVideoInfo" | "fetchCaptions" | "transcribeAudio";
