// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resolved, deduplicated link between two notes.
 */
export type GraphLink = { source: string, target: string, 
/**
 * True when source and target live in different clusters (cross-folder).
 */
bridge: boolean, };
