// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A note in the link graph — one per markdown note, orphans included.
 */
export type GraphNode = { 
/**
 * The note's `rel_path` (stable id).
 */
id: string, title: string, 
/**
 * First path segment of `rel_path`; `""` for root-level notes.
 */
cluster: string, };
