// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HardwareSpec = { totalRamBytes: number, cpuCores: number, cpuBrand: string, gpuLabel: string | null, arch: string, os: string, };
