// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HfModelMeta = { id: string, downloads: number | null, likes: number | null, lastModified: string | null, license: string | null, };
