// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstalledModel = { tag: string, sizeBytes: number, family: string | null, parameterSize: string | null, quantization: string | null, };
