// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a save or clear reports beyond "it worked". The keychain change itself is
 * committed by the time this is returned; this carries the *other* guarantee —
 * whether every other running instance was told to stop trusting what it cached.
 */
export type KeyChangeOutcome = { 
/**
 * `false` when the cross-process revision could not be published on one or
 * both sides of the keychain change. The key really is stored (or really is
 * gone), but another running instance keeps using the previous one until it
 * restarts — so this must not be reported as an unqualified success, least
 * of all for a revocation, where the user believes they revoked access.
 */
revisionPublished: boolean, };
