// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphLink } from "./GraphLink";
import type { GraphNode } from "./GraphNode";

/**
 * The whole vault's wikilink/markdown-link graph.
 */
export type LinkGraph = { nodes: Array<GraphNode>, links: Array<GraphLink>, 
/**
 * Markdown files that could not be read (their nodes remain, their
 * outgoing links are unknown; each is also logged). Lets the UI
 * distinguish "sparse graph" from "couldn't look".
 */
skippedFiles: number, };
