// This file was generated from the Rust `MARKDOWN_EXTENSIONS` constant by `cargo test`
// (crates/neuralnote-core/src/tree.rs). Do not edit this file manually.

/** File extensions the reader renders natively as Markdown, lowercased.
 *  The Rust core is the single source of truth; both sides consume this
 *  list so the tree, reader, and client classification cannot diverge. */
export const MARKDOWN_EXTENSIONS = ["md", "markdown", "mdx"] as const;
