// This file was generated from the Rust `CUSTOM_ACTIONS` constant by `cargo test`
// (app/desktop/src-tauri/src/menu.rs). Do not edit this file manually.

/** The native menu's custom action ids — the Rust core is the single
 *  source of truth (`CUSTOM_ACTIONS`). `api.ts` derives the `MenuAction`
 *  union from this list and unions in the two synthesized actions Rust
 *  emits outside it (`open-recent`, `quit-app`), so the vocabulary can
 *  never drift from the menu builder. */
export const MENU_ACTIONS = ["new-note", "new-folder", "open-vault", "close-tab", "close-window", "close-vault", "save", "search", "view-files", "view-search", "toggle-graph", "toggle-chat", "toggle-sidebar", "format-bold", "format-italic", "format-h1", "format-h2", "format-h3", "format-link"] as const;
