// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The note role that drives collision handling and the chat report card.
 */
export type NoteKind = "literature" | "atomic" | "transcript";
