// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A note opened in the reader/editor: parsed frontmatter + markdown body, with
 * the full raw file always retained so nothing is ever lost or hidden.
 */
export type NoteDoc = { path: string, relPath: string, 
/**
 * Best-effort title: frontmatter `title`, else first H1, else file stem.
 */
title: string, 
/**
 * Parsed YAML frontmatter as JSON, or `None` if absent/unparseable.
 * `serde_json::Value` has no single TS shape; the frontend has always modelled
 * a parsed frontmatter block as a string-keyed record, so pin that here rather
 * than let ts-rs emit `any` (which `strict` + the no-`any` rule forbid). The
 * `| null` is written explicitly because `#[ts(type)]` overrides the whole
 * field type, including the `| null` that `Option` would otherwise add.
 */
frontmatter: Record<string, unknown> | null, 
/**
 * The raw frontmatter block (between the `---` fences), if present.
 */
frontmatterRaw: string | null, 
/**
 * Set (failures are never silent) when a frontmatter block existed but did
 * not parse — the UI still gets `raw` + `body` to show.
 */
frontmatterError: string | null, 
/**
 * Markdown body with the frontmatter block stripped.
 */
body: string, 
/**
 * The entire file, verbatim — the safety net behind every other field.
 */
raw: string, 
/**
 * Stable content fingerprint at read. Echoed back on save so the backend can
 * detect an external edit and refuse to clobber it (optimistic concurrency).
 */
contentHash: string, 
/**
 * True for a binary attachment (image, PDF, or any non-`.md`/`.txt` file that
 * isn't valid UTF-8). The reader shows its "no preview" notice instead of an
 * error, and `body`/`raw` are empty (binary bytes are never sent across the IPC
 * boundary as a lossy string). Editing/saving is disabled for these.
 */
binary: boolean, 
/**
 * True when a *text* note (`.md`/`.txt`) was not valid UTF-8 and had to be
 * decoded lossily (e.g. a Windows-1252/Latin-1 note from a migrated vault).
 * Content is shown rather than hidden, but some bytes became `�` — the reader
 * surfaces a notice so the degradation is never silent.
 */
lossyText: boolean, };
