// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenRouterModelChoice } from "./OpenRouterModelChoice";

export type OpenRouterModelMenu = { models: Array<OpenRouterModelChoice>, asOf: string, selectedModel: string, pinnedSelectedModel: string | null, };
