// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpenRouterStatus = { hasKey: boolean, model: string, 
/**
 * Whether the user has opted into reasoning tokens. This remains on the existing
 * OpenRouter status DTO for compatibility, while both providers use the same
 * persisted opt-in.
 */
reasoning: boolean, };
