// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffortOverride } from "./ReasoningEffortOverride";

export type OpenRouterStatus = { hasKey: boolean, model: string, 
/**
 * Whether the user has opted into reasoning tokens. This remains on the existing
 * OpenRouter status DTO for compatibility, while both providers use the same
 * persisted opt-in.
 */
reasoning: boolean, 
/**
 * The effort the user picked off this model's own menu, or `null` for the
 * model's own default. Sits beside `reasoning` for the same reason it does:
 * one persisted preference, surfaced where the existing control reads it.
 *
 * Never a value we chose. It is only ever set by `set_reasoning_effort`,
 * which refuses anything the probed menu does not offer, and it is cleared
 * whenever the selected model changes.
 *
 * It is the STORED value, which since amendment E3 is not always the one on
 * the wire: a menu that shrinks under a model leaves the preference intact
 * and substitutes for the request alone (`reasoning_ask`). This field is
 * what the user chose, not what the last turn sent — `reasoning_effort_override`
 * beside it is where the two part company.
 */
reasoningEffort: string | null, 
/**
 * Present only while this model's current menu will not accept the stored
 * effort, and then carrying both halves: what the user chose, and what turns
 * are asking for instead (amendment E3).
 *
 * It exists because without it the substitution is invisible to the person
 * paying for it. A stored `xhigh` against a menu that shrank to
 * `["high", "low"]` renders the effort control blank — the value is not on
 * the list it draws from — while every turn quietly bills for `high`, and
 * the only witness is a log line no desktop user opens.
 *
 * Resolved by the same core call the send path uses, against the same
 * control this status hands the UI — one rule read twice, not two rules that
 * happen to agree. (What can still move between a poll and a turn is the
 * menu itself; the next poll reports that.) Absent is the ordinary case,
 * which is why it is an optional key rather than a null: nothing is being
 * substituted, and `reasoning_effort` above is the whole truth.
 *
 * Rendering it is a UI decision and deliberately not made here. What is
 * settled here is that the truth is available to render.
 */
reasoningEffortOverride?: ReasoningEffortOverride, };
