// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One step the model declared it intends to take. `id` is the model's own
 * handle for the step — it is the correlation key that later status updates and
 * timeline affiliations use, so it is never re-derived from `label`.
 */
export type PlanStep = { id: string, 
/**
 * A short human label. This one IS model prose, unavoidably: only the model
 * knows what it plans to do. It is rendered as a label and never matched on.
 */
label: string, };
