// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which selected video is in flight. The total is fixed for the run, unlike
 * the planning-round ceiling, which can grow when skills activate.
 */
export type PlaylistPosition = { 
/**
 * 1-based: the first selected video is 1, so it pairs directly with
 * `total` as "video 2 of 3".
 */
position: number, 
/**
 * How many videos the user selected. Constant for the run.
 */
total: number, };
