// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which item of a selected playlist is in flight.
 *
 * The denominator is the playlist's own length — fixed when the user picked the
 * videos and unable to move afterwards, unlike
 * [`ChatEvent::PlanningRound::max_rounds`], which a mid-run skill activation can
 * raise. That is the whole reason this exists: during a playlist the run's
 * progress is measured in videos, which is both the honest unit of work and the
 * only one with a stable ceiling.
 */
export type PlaylistPosition = { 
/**
 * 1-based: the first selected video is 1, so it pairs directly with
 * `total` as "video 2 of 3".
 */
position: number, 
/**
 * How many videos the user selected. Constant for the run.
 */
total: number, };
