// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PullEvent = { "type": "progress", status: string, digest: string | null, completed: number | null, total: number | null, percent: number | null, } | { "type": "success" } | { "type": "error", message: string, };
