// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One reconciled recovery outcome. Every variant is surfaced to the user; stale
 * records that recovered nothing produce no entry.
 */
export type QuarantineRecoveryStatus = "recovered" | "removedInterruptedWrite" | "conflict" | "retained";
