// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the reasoning control should offer for the selected model.
 *
 * A closed set, because the control is a rendering decision and every state the
 * probe can produce needs exactly one: an unanswered probe is not the same as a
 * model that cannot reason, and neither is a model whose reasoning is forced on.
 */
export type ReasoningControl = { "kind": "hidden" } | { "kind": "pending" } | { "kind": "toggle", defaultOn: boolean, } | { "kind": "locked" } | { "kind": "efforts", options: Array<string>, defaultEffort: string | null, canDisable: boolean, };
