// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stored reasoning effort this model's current menu will not accept, and the
 * value going out in its place (amendment E3).
 *
 * Both halves travel together because the sentence a reader needs is one
 * sentence — "you chose X; this model no longer offers it, so turns are asking
 * for Y" — and a consumer diffing two separate fields to work that out would be
 * re-deriving a decision the core already made.
 */
export type ReasoningEffortOverride = { 
/**
 * The effort the user picked, still persisted and still theirs. It comes
 * back on its own if the menu does.
 */
stored: string, 
/**
 * The effort actually being sent instead. Null for "name no effort and take
 * the provider's own default", which is what null means on the stored
 * preference beside it too.
 */
sending: string | null, };
