// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the selected model can emit reasoning tokens. `Unknown` when the
 * probe could not run (offline, a hand-typed model id, a 5xx) — callers FAIL OPEN.
 */
export type ReasoningSupport = "supported" | "unsupported" | "unknown";
