// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A recently-opened vault, for the welcome screen.
 */
export type RecentVault = { name: string, path: string, 
/**
 * Unix epoch milliseconds of the last open.
 */
lastOpened: number, };
