// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Recommendation = { "status": "supported", modelTag: string, params: string, estRamBytes: number, why: string, } | { "status": "unsupported", reason: string, };
