// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Settings-facing state for one evaluated skill requirement.
 */
export type RequirementStatus = { "status": "installed" } | { "status": "unmet", reasons: Array<string>, } | { "status": "undetected", reasons: Array<string>, } | { "status": "unmetAndUndetected", unmet: Array<string>, undetected: Array<string>, };
