// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One prerequisite a skill needs before its instructions can run.
 */
export type Requirement = { "type": "binary", name: string, } | { "type": "asset", name: string, } | { "type": "freeDiskSpace", minBytes: number, } | { "type": "platform", os: string, arch: string, };
