// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A guarded source-range edit. The adapter includes the original block IDs
 * covering the smallest contiguous changed range and its replacement Markdown.
 */
export type RichEditPatch = { expectedRevision: string, changedBlockIds: Array<string>, replacementMarkdown: string, };
