// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichEditFallback } from "./RichEditFallback";

export type RichEditDisposition = { "kind": "rich" } | { "kind": "raw", reason: RichEditFallback, };
