// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichEditBlock } from "./RichEditBlock";
import type { RichEditDisposition } from "./RichEditDisposition";

/**
 * Pure analysis result for a note already loaded as bytes by a host.
 */
export type RichEditDocument = { revision: string, frontmatterPrefix: string, body: string, disposition: RichEditDisposition, blocks: Array<RichEditBlock>, };
