// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichEditFallbackCode } from "./RichEditFallbackCode";

export type RichEditFallback = { code: RichEditFallbackCode, message: string, };
