// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A rich-editable top-level Markdown block. IDs are opaque capabilities tied to
 * the note revision and exact source range; byte offsets never cross this DTO.
 */
export type RichEditBlock = { id: string, leadingSeparator: string, markdown: string, trailingSeparator: string, };
