// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RichEditFallbackCode = "cr_lf_body" | "malformed_frontmatter" | "malformed_markdown" | "unsupported_syntax";
