// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileHit } from "./FileHit";

/**
 * The full result of a vault search.
 */
export type SearchResponse = { hits: Array<FileHit>, 
/**
 * True when a match cap clipped anything (the UI shows a banner).
 */
truncated: boolean, 
/**
 * Markdown files that could not be read and were skipped (each is also
 * logged). Lets the UI distinguish "no results" from "couldn't look".
 */
skippedFiles: number, };
