// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One matching line of a note in full-text search results.
 */
export type SearchMatch = { 
/**
 * 1-based line number in the raw file.
 */
line: number, 
/**
 * The matching line, clipped to a window around the first match when long.
 */
snippet: string, 
/**
 * Match ranges as `[start, end)` **Unicode-scalar (char) offsets into
 * `snippet`** (serialises to `[[s, e], …]`). The frontend slices the
 * snippet via `Array.from`, so both sides count code points — never bytes
 * or UTF-16 units.
 */
ranges: Array<[number, number]>, };
