// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Requirement } from "./Requirement";
import type { RequirementStatus } from "./RequirementStatus";

/**
 * One requirement paired with its host-specific Settings status.
 */
export type SkillRequirement = { requirement: Requirement, status: RequirementStatus, };
