// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillRequirement } from "./SkillRequirement";

/**
 * Compact Settings projection of a built-in skill manifest.
 */
export type SkillListing = { id: string, name: string, description: string, icon: string, enabled: boolean, requirements: Array<SkillRequirement>, };
