// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a declared step has got to.
 *
 * `Skipped` and `Failed` are separate on purpose, for the same reason
 * [`ToolStatus`](crate::ai::events::ToolStatus) splits its refusals: "I decided
 * this was unnecessary" and "I tried this and it did not work" are two different
 * accounts of the same missing work, and only one of them is a problem.
 */
export type StepStatus = "pending" | "running" | "done" | "skipped" | "failed";
