// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateSettings } from "./TemplateSettings";
import type { TemplateSettingsSource } from "./TemplateSettingsSource";

export type TemplateSettingsStatus = { settings: TemplateSettings, source: TemplateSettingsSource, folderExists: boolean, };
