// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One markdown template available for note creation.
 */
export type TemplateInfo = { 
/**
 * Vault-relative path to the template file.
 */
relPath: string, 
/**
 * Display name, derived from the template file stem.
 */
name: string, };
