// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which model phase produced a Thinking delta.
 */
export type ThinkingSource = "toolTurn" | "finalAnswer";
