// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a dispatched tool call settled. Validation refusal (`Rejected`), execution
 * failure (`Error`), user denial, prompt timeout, and run cancellation remain
 * distinct so the UI accurately attributes the outcome.
 */
export type ToolStatus = "ok" | "error" | "denied" | "timedOut" | "cancelled" | "rejected";
