// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a dispatched tool call settled. Mirrors [`crate::ai::tools::ToolOutcome`]'s
 * discriminant but is the UI-facing vocabulary: `Rejected` (bad args/path — the
 * orchestrator refused) and `Denied` (the user refused) are different stories and
 * must render differently.
 *
 * Two of the four have no producer yet, on purpose — this is the frozen wire
 * contract the UI renders against, and both have a named owner:
 * - `Denied` arrives with the tool-approval gate, which is what makes a user
 *   refusal distinguishable from an orchestrator rejection.
 * - `Error` arrives when `ToolOutcome` gains a discriminant for "the tool ran and
 *   failed"; today every failure — malformed arguments and runtime failure alike —
 *   is one `ToolOutcome::Rejected`, so reporting `Error` would be a guess.
 */
export type ToolStatus = "ok" | "error" | "denied" | "rejected";
