// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a dispatched tool call settled. Mirrors [`crate::ai::tools::ToolOutcome`]'s
 * discriminant but is the UI-facing vocabulary: `Rejected` (bad args/path — the
 * orchestrator refused) and `Denied` (the user refused) are different stories and
 * must render differently.
 *
 * The three ways the approval gate can settle a call it ASKED about are three
 * separate statuses — `Denied`, `TimedOut`, `Cancelled` — and the split is the
 * point. All three mean "the call did not run", but they attribute it to three
 * different parties: the user said no, nobody answered inside 120s, or the run
 * went away underneath the question. Folding them into `Denied` tells a user who
 * never saw the sheet that they refused something, which is the one account that
 * is definitely false. `ApprovalResolution` already distinguishes them on the
 * wire — §9.2 says it exists precisely so a timeout or a window close is visible
 * — so collapsing here threw the distinction away at the last step.
 *
 * A call the gate refuses WITHOUT asking (a vault escape, an invalid path)
 * settles as `Rejected` instead: that is validation, not a decision anyone made.
 *
 * `ApprovalResolution::Unavailable` has no counterpart here and needs none: it is
 * emitted *before* a prompt, to explain the pause, and is always followed by one
 * of the three above.
 *
 * What goes red if these are re-collapsed:
 * `a_timeout_is_not_reported_as_a_user_denial`, in `orchestrator.rs`'s
 * `settlement_tests`, which is where the mapping from `ApprovalResolution` to
 * this enum actually lives.
 *
 * `Error` is produced by `ToolOutcome::Failed` — a call that reached the vault,
 * the network, or the extractor and came apart there (#116). It used to have no
 * producer, because `ToolOutcome` could not tell that apart from a call the
 * dispatcher refused; both arrived as one `Rejected`, and the timeline told the
 * user NeuralNote had declined work it had in fact attempted.
 *
 * The dividing line is whether anything was tried. Malformed arguments, an
 * unknown or unauthorised tool, a path outside the vault, a URL outside the
 * playlist the user picked: all `Rejected`, because the system protected the
 * user and nothing is broken. Everything past that point is `Error`.
 *
 * What goes red if they are re-collapsed:
 * `a_malformed_argument_call_is_refused_and_never_collapses_into_a_failure`,
 * in `orchestrator.rs`'s `tests`, which asserts the two settle differently in
 * one run rather than merely asserting each in isolation.
 */
export type ToolStatus = "ok" | "error" | "denied" | "timedOut" | "cancelled" | "rejected";
