// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryKind } from "./EntryKind";

/**
 * A node in the vault file tree. Folders carry `children`; files carry `ext`.
 */
export type TreeNode = { kind: EntryKind, 
/**
 * Final path component (file or folder name).
 */
name: string, 
/**
 * Absolute path on disk.
 */
path: string, 
/**
 * Path relative to the vault root, `/`-joined (stable id for the UI).
 */
relPath: string, 
/**
 * Lowercased file extension without the dot (files only; `None` for folders).
 */
ext: string | null, 
/**
 * Child nodes (folders only; `None` for files), folders-first then files,
 * each group sorted case-insensitively by name.
 */
children: Array<TreeNode> | null, };
