// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryKind } from "./EntryKind";

/**
 * A node in the vault file tree. Folders carry `children`; files carry `ext`.
 */
export type TreeNode = { kind: EntryKind, 
/**
 * Final path component (file or folder name).
 */
name: string, 
/**
 * Absolute path on disk.
 */
path: string, 
/**
 * Path relative to the vault root, `/`-joined (stable id for the UI).
 */
relPath: string, 
/**
 * Lowercased file extension without the dot (files only; `None` for folders).
 */
ext: string | null, 
/**
 * Child nodes (folders only; `None` for files), folders-first then files,
 * each group sorted case-insensitively by name. NOTE the overload: from the
 * eager [`crate::tree::read_tree`] a folder's `None` never occurs (it carries
 * `Some`, empty for an empty folder), but from the lazy
 * [`crate::tree::list_dir`] a folder carries `None` to mean "not loaded yet".
 * So `children.unwrap_or_default()` is a correct note-count ONLY over an eager
 * tree; never treat a lazy node's `None` as "empty folder".
 */
children: Array<TreeNode> | null, };
