// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-file Undo outcome. Every non-deletion carries a user-facing reason.
 */
export type UndoFileStatus = "deleted" | "skippedEdited" | "skippedMissing" | "failed";
