// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UndoFileStatus } from "./UndoFileStatus";

export type UndoFileResult = { relPath: string, status: UndoFileStatus, message: string | null, };
