// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One note whose body mentions the current note title without linking it.
 */
export type UnlinkedMention = { sourceRel: string, sourceTitle: string, snippet: string, 
/**
 * 1-based line number in the source note body.
 */
line: number, };
