// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An opened vault — just a folder on disk, by design. Any folder is a valid
 * vault (that is what makes "open your existing Obsidian vault" zero-migration).
 */
export type Vault = { 
/**
 * Display name (the folder's final path component).
 */
name: string, 
/**
 * Absolute path to the vault root.
 */
path: string, };
